<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><TargetFramework>net8.0</TargetFramework><ImplicitUsings>enable</ImplicitUsings><Nullable>enable</Nullable></PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Seven.AutoERP.Fiscal\Seven.AutoERP.Fiscal.csproj" />
    <PackageReference Include="Zeus.Net.NFe.Danfe.Html" Version="2026.8.18.2047" />
  </ItemGroup>
</Project>
