"use client";

type Row = Record<string, any>;
const money = new Intl.NumberFormat("pt-BR", { minimumFractionDigits: 2, maximumFractionDigits: 2 });
const qty = new Intl.NumberFormat("pt-BR", { minimumFractionDigits: 0, maximumFractionDigits: 4 });
const text=(v:unknown)=>String(v??"").trim();
const num=(v:unknown)=>{const n=Number(v);return Number.isFinite(n)?n:null};
const moneyOrBlank=(v:unknown)=>{const n=num(v);return n===null?"":money.format(n)};
const cents=(v:unknown)=>{const n=num(v);return n===null?null:n/100};
const digits=(v:unknown)=>text(v).replace(/\D/g,"");
const fmtTax=(v:unknown)=>{const r=digits(v);if(r.length===14)return r.replace(/^(\d{2})(\d{3})(\d{3})(\d{4})(\d{2})$/,"$1.$2.$3/$4-$5");if(r.length===11)return r.replace(/^(\d{3})(\d{3})(\d{3})(\d{2})$/,"$1.$2.$3-$4");return text(v)};
const fmtCep=(v:unknown)=>{const r=digits(v);return r.length===8?r.replace(/^(\d{5})(\d{3})$/,"$1-$2"):text(v)};
const fmtDate=(v:unknown)=>{if(!v)return "";const d=new Date(String(v));return Number.isNaN(d.getTime())?text(v):d.toLocaleDateString("pt-BR")};
const fmtTime=(v:unknown)=>{if(!v)return "";const d=new Date(String(v));return Number.isNaN(d.getTime())?"":d.toLocaleTimeString("pt-BR",{hour:"2-digit",minute:"2-digit"})};
const keyText=(v:unknown)=>text(v).toUpperCase().replace(/[^A-Z0-9]/g,"").replace(/(.{4})/g,"$1 ").trim();
const choose=(source:Row,...keys:string[])=>{for(const k of keys){if(source[k]!==undefined&&source[k]!==null&&String(source[k])!=="")return source[k]}return ""};

const CODE128=["212222","222122","222221","121223","121322","131222","122213","122312","132212","221213","221312","231212","112232","122132","122231","113222","123122","123221","223211","221132","221231","213212","223112","312131","311222","321122","321221","312212","322112","322211","212123","212321","232121","111323","131123","131321","112313","132113","132311","211313","231113","231311","112133","112331","132131","113123","113321","133121","313121","211331","231131","213113","213311","213131","311123","311321","331121","312113","312311","332111","314111","221411","431111","111224","111422","121124","121421","141122","141221","112214","112412","122114","122411","142112","142211","241211","221114","413111","241112","134111","111242","121142","121241","114212","124112","124211","411212","421112","421211","212141","214121","412121","111143","111341","131141","114113","114311","411113","411311","113141","114131","311141","411131","211412","211214","211232","2331112"];
function numericRun(value:string,index:number){let end=index;while(end<value.length&&/\d/.test(value[end]))end++;return end-index}
function encode128(value:string){const input=value.toUpperCase().replace(/[^A-Z0-9]/g,"");if(!input)return [];let mode=numericRun(input,0)>=4?"C":"B";const codes=[mode==="C"?105:104];let index=0;while(index<input.length){if(mode==="C"){const run=numericRun(input,index);if(run>=2){const usable=run-(run%2);for(let o=0;o<usable;o+=2)codes.push(Number(input.slice(index+o,index+o+2)));index+=usable;continue}codes.push(100);mode="B";continue}const run=numericRun(input,index);if(run>=4){if(run%2===1){codes.push(input.charCodeAt(index)-32);index++}codes.push(99);mode="C";continue}const code=input.charCodeAt(index)-32;if(code<0||code>95)return [];codes.push(code);index++}let checksum=codes[0];for(let i=1;i<codes.length;i++)checksum+=codes[i]*i;codes.push(checksum%103,106);return codes}
function Barcode({value}:{value:string}){const codes=encode128(value);if(!codes.length)return <div className="danfe3-no-barcode">CHAVE AINDA NÃO GERADA</div>;let cursor=10;const rects:{x:number,w:number}[]=[];for(const code of codes){let bar=true;for(const digit of CODE128[code]){const width=Number(digit);if(bar)rects.push({x:cursor,w:width});cursor+=width;bar=!bar}}const total=cursor+10;return <svg className="danfe3-barcode" viewBox={`0 0 ${total} 50`} preserveAspectRatio="none" aria-label="Código de barras Code 128 da chave de acesso">{rects.map((r,i)=><rect key={i} x={r.x} y="0" width={r.w} height="50" />)}</svg>}
function Field({label,value,wide=false,strong=false}:{label:string;value:unknown;wide?:boolean;strong?:boolean}){return <div className={`danfe3-field${wide?" wide":""}${strong?" strong":""}`}><span>{label}</span><b>{text(value)}</b></div>}
function splitItems(items:Row[]){const pages:Row[][]=[];let current:Row[]=[],weight=0,capacity=12;for(const item of items){const w=1+Math.max(0,Math.ceil(text(item.description||item.xProd).length/58)-1)*.55;if(current.length&&weight+w>capacity){pages.push(current);current=[];weight=0;capacity=30}current.push(item);weight+=w}if(current.length||!pages.length)pages.push(current);return pages}
function itemQty(i:Row){if(i.quantity!==undefined)return num(i.quantity)||0;if(i.quantityMilli!==undefined)return (num(i.quantityMilli)||0)/1000;return num(i.qCom)||0}
function itemUnit(i:Row){if(i.unitPrice!==undefined)return num(i.unitPrice)||0;if(i.unitPriceCents!==undefined)return (num(i.unitPriceCents)||0)/100;return num(i.vUnCom)||0}
function itemTotal(i:Row){const direct=choose(i,"total","productValue","vProd");if(direct!=="")return num(direct)||0;if(i.totalCents!==undefined)return (num(i.totalCents)||0)/100;return itemQty(i)*itemUnit(i)}
function freightLabel(v:unknown){const m:Record<string,string>={sender:"0 - Remetente (CIF)",recipient:"1 - Destinatário (FOB)",third_party:"2 - Terceiros",no_freight:"9 - Sem transporte","0":"0 - Remetente (CIF)","1":"1 - Destinatário (FOB)","2":"2 - Terceiros","9":"9 - Sem transporte"};return m[text(v)]||text(v)}

export default function NfeDanfePreviewV3({draft,company,snapshot}:{draft:Row;company:Row;snapshot?:Row}){
 const source={...draft,...(snapshot||{})};const items:Row[]=Array.isArray(snapshot?.items)?snapshot!.items:Array.isArray(draft.items)?draft.items:[];const pages=splitItems(items);
 const status=text(draft.transmissionStatus||draft.transmission?.status||"draft"),authorized=status==="authorized",cancelled=status==="cancelled";
 const accessKey=text(draft.accessKey||draft.transmission?.accessKey),protocol=text(draft.protocol||draft.transmission?.protocol),number=draft.nfeNumber||draft.transmission?.number||"",series=draft.nfeSeries||draft.transmission?.series||company.nfeSeries||"";
 const issueAt=choose(source,"issuedAt","issueDate",draft.transmission?.issuedAt?"transmissionIssuedAt":"")||draft.transmission?.issuedAt||draft.createdAt;const exitAt=choose(source,"exitAt","departureAt","dhSaiEnt");
 const products=cents(draft.productsTotalCents)??items.reduce((sum,i)=>sum+itemTotal(i),0);const freight=choose(source,"freight")!==""?num(source.freight):cents(draft.freightCents);const insurance=choose(source,"insurance")!==""?num(source.insurance):cents(draft.insuranceCents);const discount=choose(source,"discount")!==""?num(source.discount):cents(draft.discountCents);const other=choose(source,"other")!==""?num(source.other):cents(draft.otherCents);const total=cents(draft.totalCents)??Math.max(0,products+(freight||0)+(insurance||0)+(other||0)-(discount||0));
 const tax={bc:choose(source,"icmsBase","baseIcms","vBC"),icms:choose(source,"icmsValue","icms","vICMS"),bcst:choose(source,"icmsStBase","baseIcmsSt","vBCST"),st:choose(source,"icmsStValue","icmsSt","vST"),ipi:choose(source,"ipiValue","ipi","vIPI"),trib:choose(source,"totalTaxes","vTotTrib")};
 const issuerName=company.tradeName||company.legalName||"EMPRESA NÃO CADASTRADA";const watermark=cancelled?"CANCELADA":source.environment!=="production"?"SEM VALOR FISCAL · HOMOLOGAÇÃO":!authorized?"ESPELHO · SEM VALOR FISCAL":"ESPELHO";
 return <div className="danfe3-pages">{pages.map((pageItems,pageIndex)=><article className="danfe3-sheet" key={pageIndex}><div className="danfe3-watermark">{watermark}</div>{pageIndex===0&&<section className="danfe3-receipt danfe3-box"><div><p>RECEBEMOS DE {issuerName} OS PRODUTOS E/OU SERVIÇOS CONSTANTES DA NF-e INDICADA AO LADO. EMISSÃO: {fmtDate(issueAt)} · VALOR TOTAL: R$ {money.format(total)} · DESTINATÁRIO: {text(source.recipientName)}.</p><div className="danfe3-sign"><span>DATA DE RECEBIMENTO</span><span>IDENTIFICAÇÃO E ASSINATURA DO RECEBEDOR</span></div></div><aside><b>NF-e</b><strong>Nº {number?String(number).padStart(9,"0"):"000.000.000"}</strong><span>SÉRIE {series||"—"}</span></aside></section>}
 <section className="danfe3-head danfe3-box"><div className="danfe3-issuer"><small>IDENTIFICAÇÃO DO EMITENTE</small><h1>{issuerName}</h1><b>{company.legalName}</b><p>{[company.street,company.number,company.complement].filter(Boolean).join(", ")}</p><p>{[company.district,company.city,company.state].filter(Boolean).join(" - ")} {company.postalCode?`· CEP ${fmtCep(company.postalCode)}`:""}</p></div><div className="danfe3-title"><h2>DANFE</h2><p>Documento Auxiliar da Nota Fiscal Eletrônica</p><div className="danfe3-flow"><span>0 - ENTRADA<br/>1 - SAÍDA</span><b>{text(source.operationType||source.tpNF).startsWith("0")?"0":"1"}</b></div><strong>Nº {number?String(number).padStart(9,"0"):"000.000.000"}</strong><strong>SÉRIE {series||"—"}</strong><small>FOLHA {pageIndex+1}/{pages.length}</small></div><div className="danfe3-key"><Barcode value={accessKey}/><span>CHAVE DE ACESSO</span><b>{accessKey?keyText(accessKey):"CHAVE AINDA NÃO GERADA"}</b><p>Consulta no Portal Nacional da NF-e ou no site da Sefaz autorizadora.</p></div></section>
 <section className="danfe3-row danfe3-box"><Field label="NATUREZA DA OPERAÇÃO" value={source.natureOperation} wide/><Field label="PROTOCOLO DE AUTORIZAÇÃO DE USO" value={protocol||(!authorized?"AINDA NÃO AUTORIZADA":"")} wide/></section><section className="danfe3-row danfe3-box"><Field label="INSCRIÇÃO ESTADUAL" value={company.stateRegistration}/><Field label="INSCRIÇÃO ESTADUAL DO SUBST. TRIBUT." value={company.stateRegistrationSt}/><Field label="CNPJ / CPF" value={fmtTax(company.taxId)}/></section>
 {pageIndex===0&&<><h3 className="danfe3-caption">DESTINATÁRIO / REMETENTE</h3><section className="danfe3-box"><div className="danfe3-row"><Field label="NOME / RAZÃO SOCIAL" value={source.recipientName} wide/><Field label="CNPJ / CPF" value={fmtTax(source.recipientTaxId)}/><Field label="DATA DA EMISSÃO" value={fmtDate(issueAt)}/></div><div className="danfe3-row"><Field label="ENDEREÇO" value={[source.recipientStreet,source.recipientNumber,source.recipientComplement].filter(Boolean).join(", ")} wide/><Field label="BAIRRO / DISTRITO" value={source.recipientDistrict}/><Field label="CEP" value={fmtCep(source.recipientPostalCode)}/><Field label="DATA DA SAÍDA / ENTRADA" value={fmtDate(exitAt)}/></div><div className="danfe3-row"><Field label="MUNICÍPIO" value={source.recipientCity} wide/><Field label="FONE / FAX" value={source.recipientPhone}/><Field label="UF" value={source.recipientState}/><Field label="INSCRIÇÃO ESTADUAL" value={source.recipientStateRegistration}/><Field label="HORA DA SAÍDA" value={fmtTime(exitAt)}/></div></section><h3 className="danfe3-caption">CÁLCULO DO IMPOSTO</h3><section className="danfe3-box"><div className="danfe3-six"><Field label="BASE ICMS" value={moneyOrBlank(tax.bc)}/><Field label="VALOR ICMS" value={moneyOrBlank(tax.icms)}/><Field label="BASE ICMS ST" value={moneyOrBlank(tax.bcst)}/><Field label="VALOR ICMS ST" value={moneyOrBlank(tax.st)}/><Field label="VALOR IPI" value={moneyOrBlank(tax.ipi)}/><Field label="TOTAL PRODUTOS" value={money.format(products)}/></div><div className="danfe3-six"><Field label="FRETE" value={freight===null?"":money.format(freight||0)}/><Field label="SEGURO" value={insurance===null?"":money.format(insurance||0)}/><Field label="DESCONTO" value={discount===null?"":money.format(discount||0)}/><Field label="OUTRAS DESPESAS" value={other===null?"":money.format(other||0)}/><Field label="TRIBUTOS APROX." value={moneyOrBlank(tax.trib)}/><Field label="VALOR TOTAL NF-e" value={money.format(total)} strong/></div></section><h3 className="danfe3-caption">TRANSPORTADOR / VOLUMES TRANSPORTADOS</h3><section className="danfe3-box"><div className="danfe3-row"><Field label="NOME / RAZÃO SOCIAL" value={source.carrierName} wide/><Field label="FRETE POR CONTA" value={freightLabel(source.freightMode)}/><Field label="CÓDIGO ANTT / RNTC" value={source.anttCode||source.rntc}/><Field label="PLACA" value={source.vehiclePlate}/><Field label="UF" value={source.vehicleState}/><Field label="CNPJ / CPF" value={fmtTax(source.carrierTaxId)}/></div><div className="danfe3-six"><Field label="QUANTIDADE" value={source.volumeQuantity}/><Field label="ESPÉCIE" value={source.volumeSpecies}/><Field label="MARCA" value={source.volumeBrand}/><Field label="NUMERAÇÃO" value={source.volumeNumbering}/><Field label="PESO BRUTO" value={source.grossWeight}/><Field label="PESO LÍQUIDO" value={source.netWeight}/></div></section></>}
 <h3 className="danfe3-caption">{pageIndex===0?"DADOS DOS PRODUTOS / SERVIÇOS":"CONTINUAÇÃO DOS PRODUTOS / SERVIÇOS"}</h3><section className="danfe3-products danfe3-box"><table><thead><tr><th>CÓDIGO</th><th>DESCRIÇÃO</th><th>NCM/SH</th><th>CST</th><th>CFOP</th><th>UN</th><th>QTD.</th><th>V.UNIT.</th><th>V.TOTAL</th><th>BC ICMS</th><th>V.ICMS</th><th>V.IPI</th><th>%ICMS</th><th>%IPI</th></tr></thead><tbody>{pageItems.map((i,index)=><tr key={i.id||index}><td>{text(i.code)}</td><td>{text(i.description)}</td><td>{text(i.ncm)}</td><td>{text(i.cst||i.csosn)}</td><td>{text(i.cfop)}</td><td>{text(i.unit)}</td><td className="n">{qty.format(itemQty(i))}</td><td className="n">{money.format(itemUnit(i))}</td><td className="n">{money.format(itemTotal(i))}</td><td className="n">{moneyOrBlank(choose(i,"icmsBase","baseIcms","vBC"))}</td><td className="n">{moneyOrBlank(choose(i,"icmsValue","icms","vICMS"))}</td><td className="n">{moneyOrBlank(choose(i,"ipiValue","ipi","vIPI"))}</td><td className="n">{text(choose(i,"icmsRate","pICMS"))}</td><td className="n">{text(choose(i,"ipiRate","pIPI"))}</td></tr>)}</tbody></table></section>{pageIndex===pages.length-1&&<><h3 className="danfe3-caption">DADOS ADICIONAIS</h3><section className="danfe3-additional danfe3-box"><div><span>INFORMAÇÕES COMPLEMENTARES</span><p>{text(source.notes||source.additionalInfo)}</p>{!authorized&&<b>ESPELHO DE CONFERÊNCIA — SEM VALOR FISCAL.</b>}</div><div><span>RESERVADO AO FISCO</span></div></section></>}<footer className="danfe3-footer"><span>Seven ERP 1.0.5 · NF-e modelo 55</span><span>{accessKey?keyText(accessKey):"SEM CHAVE FISCAL"}</span></footer></article>)}</div>
}
