import { index, integer, sqliteTable, text, uniqueIndex } from "drizzle-orm/sqlite-core";
import { organizations, fiscalDocuments } from "./schema";

export const documentTemplates = sqliteTable("document_templates", {
  id: text("id").primaryKey(), organizationId: text("organization_id").notNull().references(() => organizations.id), documentType: text("document_type").notNull(), name: text("name").notNull(), description: text("description").notNull().default(""), isDefault: integer("is_default", { mode: "boolean" }).notNull().default(false), currentVersion: integer("current_version").notNull().default(1), schemaVersion: integer("schema_version").notNull().default(1), definitionJson: text("definition_json").notNull(), createdBy: text("created_by"), createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull(), updatedAt: integer("updated_at", { mode: "timestamp_ms" }).notNull(), archivedAt: integer("archived_at", { mode: "timestamp_ms" }),
}, (table) => ({ orgTypeIdx: index("document_templates_org_type_idx").on(table.organizationId, table.documentType) }));

export const documentTemplateVersions = sqliteTable("document_template_versions", {
  id: text("id").primaryKey(), templateId: text("template_id").notNull().references(() => documentTemplates.id), version: integer("version").notNull(), schemaVersion: integer("schema_version").notNull().default(1), definitionJson: text("definition_json").notNull(), note: text("note").notNull().default(""), createdBy: text("created_by"), createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull(),
}, (table) => ({ versionUq: uniqueIndex("document_template_versions_template_version_uq").on(table.templateId, table.version) }));

export const fiscalDocumentItems = sqliteTable("fiscal_document_items", {
  id: text("id").primaryKey(), fiscalDocumentId: text("fiscal_document_id").notNull().references(() => fiscalDocuments.id), lineNumber: integer("line_number").notNull(), catalogItemId: text("catalog_item_id"), code: text("code"), description: text("description").notNull(), ncm: text("ncm"), cest: text("cest"), cfop: text("cfop"), unit: text("unit"), quantityMilli: integer("quantity_milli").notNull().default(0), unitValueCents: integer("unit_value_cents").notNull().default(0), discountCents: integer("discount_cents").notNull().default(0), totalCents: integer("total_cents").notNull().default(0), taxJson: text("tax_json").notNull().default("{}"), createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull(),
}, (table) => ({ docLineUq: uniqueIndex("fiscal_document_items_doc_line_uq").on(table.fiscalDocumentId, table.lineNumber) }));

export const fiscalEvents = sqliteTable("fiscal_events", {
  id: text("id").primaryKey(), fiscalDocumentId: text("fiscal_document_id").references(() => fiscalDocuments.id), organizationId: text("organization_id").notNull().references(() => organizations.id), eventType: text("event_type").notNull(), eventSequence: integer("event_sequence").notNull().default(1), status: text("status").notNull(), environment: text("environment").notNull(), accessKey: text("access_key"), protocol: text("protocol"), requestXmlSha256: text("request_xml_sha256"), responseXmlSha256: text("response_xml_sha256"), requestXmlFileId: text("request_xml_file_id"), responseXmlFileId: text("response_xml_file_id"), userId: text("user_id"), reason: text("reason"), providerResponse: text("provider_response"), createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull(),
}, (table) => ({ documentIdx: index("fiscal_events_doc_idx").on(table.fiscalDocumentId, table.createdAt), accessKeyIdx: index("fiscal_events_access_key_idx").on(table.accessKey) }));

export const fiscalXmlFiles = sqliteTable("fiscal_xml_files", {
  id: text("id").primaryKey(), organizationId: text("organization_id").notNull().references(() => organizations.id), fiscalDocumentId: text("fiscal_document_id").references(() => fiscalDocuments.id), fiscalEventId: text("fiscal_event_id").references(() => fiscalEvents.id), kind: text("kind").notNull(), accessKey: text("access_key"), protocol: text("protocol"), sha256: text("sha256").notNull(), contentXml: text("content_xml").notNull(), immutable: integer("immutable", { mode: "boolean" }).notNull().default(true), createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull(),
}, (table) => ({ hashKindUq: uniqueIndex("fiscal_xml_files_hash_kind_uq").on(table.organizationId, table.sha256, table.kind), accessKeyIdx: index("fiscal_xml_files_access_key_idx").on(table.accessKey) }));

export const fiscalConfigurations = sqliteTable("fiscal_configurations", {
  id: text("id").primaryKey(), organizationId: text("organization_id").notNull().references(() => organizations.id), documentModel: text("document_model").notNull(), environment: text("environment").notNull().default("homologation"), provider: text("provider").notNull(), enabled: integer("enabled", { mode: "boolean" }).notNull().default(false), configurationJson: text("configuration_json").notNull().default("{}"), revision: integer("revision").notNull().default(1), updatedBy: text("updated_by"), createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull(), updatedAt: integer("updated_at", { mode: "timestamp_ms" }).notNull(),
}, (table) => ({ orgModelUq: uniqueIndex("fiscal_configurations_org_model_uq").on(table.organizationId, table.documentModel) }));

export const certificates = sqliteTable("certificates", {
  id: text("id").primaryKey(), organizationId: text("organization_id").notNull().references(() => organizations.id), certificateType: text("certificate_type").notNull(), vaultReference: text("vault_reference").notNull(), subject: text("subject"), issuer: text("issuer"), serialNumber: text("serial_number"), thumbprintSha256: text("thumbprint_sha256"), validFrom: integer("valid_from", { mode: "timestamp_ms" }), validTo: integer("valid_to", { mode: "timestamp_ms" }), status: text("status").notNull().default("active"), createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull(), updatedAt: integer("updated_at", { mode: "timestamp_ms" }).notNull(),
}, (table) => ({ vaultRefUq: uniqueIndex("certificates_org_vault_ref_uq").on(table.organizationId, table.vaultReference) }));

export const nfeConfigurations = sqliteTable("nfe_configurations", {
  id: text("id").primaryKey(), organizationId: text("organization_id").notNull().references(() => organizations.id), model: text("model").notNull().default("55"), environment: text("environment").notNull().default("homologation"), series: integer("series").notNull().default(1), nextNumber: integer("next_number").notNull().default(1), certificateId: text("certificate_id").references(() => certificates.id), contingencyMode: text("contingency_mode").notNull().default("normal"), cscVaultReference: text("csc_vault_reference"), cscId: text("csc_id"), danfeOrientation: text("danfe_orientation").notNull().default("portrait"), danfeCopies: integer("danfe_copies").notNull().default(1), printerName: text("printer_name"), previewBeforePrint: integer("preview_before_print", { mode: "boolean" }).notNull().default(true), autoPrintAfterAuthorization: integer("auto_print_after_authorization", { mode: "boolean" }).notNull().default(false), revision: integer("revision").notNull().default(1), createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull(), updatedAt: integer("updated_at", { mode: "timestamp_ms" }).notNull(),
}, (table) => ({ orgModelUq: uniqueIndex("nfe_configurations_org_model_uq").on(table.organizationId, table.model) }));

export const nfseConfigurations = sqliteTable("nfse_configurations", {
  id: text("id").primaryKey(), organizationId: text("organization_id").notNull().references(() => organizations.id), environment: text("environment").notNull().default("homologation"), provider: text("provider").notNull().default("padrao_nacional"), municipalityCode: text("municipality_code").notNull(), municipalRegistration: text("municipal_registration"), certificateId: text("certificate_id").references(() => certificates.id), baseUrl: text("base_url"), providerOptionsJson: text("provider_options_json").notNull().default("{}"), credentialVaultReference: text("credential_vault_reference"), revision: integer("revision").notNull().default(1), createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull(), updatedAt: integer("updated_at", { mode: "timestamp_ms" }).notNull(),
}, (table) => ({ orgMunicipalityUq: uniqueIndex("nfse_configurations_org_municipality_uq").on(table.organizationId, table.municipalityCode, table.provider) }));
