import { sql } from "drizzle-orm";
import { index, integer, sqliteTable, text, uniqueIndex } from "drizzle-orm/sqlite-core";

export const organizations = sqliteTable("organizations", {
  id: text("id").primaryKey(),
  legalName: text("legal_name").notNull(),
  tradeName: text("trade_name").notNull(),
  taxId: text("tax_id"),
  stateRegistration: text("state_registration"),
  municipalRegistration: text("municipal_registration"),
  taxRegime: text("tax_regime"),
  cityCode: text("city_code"),
  state: text("state"),
  status: text("status").notNull().default("active"),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
}, (table) => [uniqueIndex("organizations_tax_id_idx").on(table.taxId)]);

export const organizationMembers = sqliteTable("organization_members", {
  id: text("id").primaryKey(),
  organizationId: text("organization_id").notNull().references(() => organizations.id),
  email: text("email").notNull(),
  displayName: text("display_name").notNull(),
  role: text("role").notNull().default("operator"),
  status: text("status").notNull().default("active"),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
}, (table) => [uniqueIndex("members_org_email_idx").on(table.organizationId, table.email)]);

export const organizationSubscriptions = sqliteTable("organization_subscriptions", {
  id: text("id").primaryKey(),
  organizationId: text("organization_id").notNull().references(() => organizations.id),
  deploymentMode: text("deployment_mode").notNull().default("saas"),
  planCode: text("plan_code").notNull().default("seven_internal"),
  status: text("status").notNull().default("active"),
  seats: integer("seats").notNull().default(1),
  billingCycle: text("billing_cycle").notNull().default("monthly"),
  billingCustomerReference: text("billing_customer_reference"),
  trialEndsAt: text("trial_ends_at"),
  nextBillingDate: text("next_billing_date"),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
}, (table) => [uniqueIndex("subscriptions_org_idx").on(table.organizationId)]);

export const parties = sqliteTable("parties", {
  id: text("id").primaryKey(),
  organizationId: text("organization_id").notNull().references(() => organizations.id),
  kind: text("kind").notNull().default("customer"),
  personType: text("person_type").notNull().default("legal"),
  legalName: text("legal_name").notNull(),
  tradeName: text("trade_name"),
  taxId: text("tax_id"),
  stateRegistration: text("state_registration"),
  municipalRegistration: text("municipal_registration"),
  email: text("email"),
  phone: text("phone"),
  postalCode: text("postal_code"),
  street: text("street"),
  number: text("number"),
  district: text("district"),
  city: text("city"),
  cityCode: text("city_code"),
  state: text("state"),
  notes: text("notes"),
  status: text("status").notNull().default("active"),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
}, (table) => [index("parties_org_kind_idx").on(table.organizationId, table.kind), index("parties_tax_id_idx").on(table.taxId)]);

export const catalogItems = sqliteTable("catalog_items", {
  id: text("id").primaryKey(),
  organizationId: text("organization_id").notNull().references(() => organizations.id),
  type: text("type").notNull().default("product"),
  sku: text("sku"),
  name: text("name").notNull(),
  description: text("description"),
  ncm: text("ncm"),
  cest: text("cest"),
  serviceCode: text("service_code"),
  unit: text("unit").notNull().default("UN"),
  costCents: integer("cost_cents").notNull().default(0),
  priceCents: integer("price_cents").notNull().default(0),
  stockQuantityMilli: integer("stock_quantity_milli").notNull().default(0),
  minimumStockMilli: integer("minimum_stock_milli").notNull().default(0),
  status: text("status").notNull().default("active"),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
}, (table) => [uniqueIndex("catalog_org_sku_idx").on(table.organizationId, table.sku), index("catalog_org_type_idx").on(table.organizationId, table.type)]);

export const commercialDocuments = sqliteTable("commercial_documents", {
  id: text("id").primaryKey(),
  organizationId: text("organization_id").notNull().references(() => organizations.id),
  partyId: text("party_id").references(() => parties.id),
  type: text("type").notNull().default("quote"),
  number: integer("number").notNull(),
  series: text("series").notNull().default("1"),
  status: text("status").notNull().default("draft"),
  issuedAt: text("issued_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  validUntil: text("valid_until"),
  subtotalCents: integer("subtotal_cents").notNull().default(0),
  discountCents: integer("discount_cents").notNull().default(0),
  freightCents: integer("freight_cents").notNull().default(0),
  totalCents: integer("total_cents").notNull().default(0),
  notes: text("notes"),
  createdBy: text("created_by"),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
}, (table) => [uniqueIndex("commercial_org_type_number_idx").on(table.organizationId, table.type, table.series, table.number), index("commercial_party_idx").on(table.partyId)]);

export const commercialDocumentItems = sqliteTable("commercial_document_items", {
  id: text("id").primaryKey(),
  documentId: text("document_id").notNull().references(() => commercialDocuments.id),
  catalogItemId: text("catalog_item_id").references(() => catalogItems.id),
  description: text("description").notNull(),
  quantityMilli: integer("quantity_milli").notNull().default(1000),
  unitPriceCents: integer("unit_price_cents").notNull().default(0),
  discountCents: integer("discount_cents").notNull().default(0),
  totalCents: integer("total_cents").notNull().default(0),
  taxSnapshotJson: text("tax_snapshot_json"),
}, (table) => [index("commercial_items_document_idx").on(table.documentId)]);

export const serviceOrders = sqliteTable("service_orders", {
  id: text("id").primaryKey(),
  organizationId: text("organization_id").notNull().references(() => organizations.id),
  partyId: text("party_id").notNull().references(() => parties.id),
  number: integer("number").notNull(),
  status: text("status").notNull().default("open"),
  priority: text("priority").notNull().default("normal"),
  equipmentType: text("equipment_type"),
  equipmentBrand: text("equipment_brand"),
  equipmentModel: text("equipment_model"),
  serialNumber: text("serial_number"),
  reportedIssue: text("reported_issue").notNull(),
  diagnosis: text("diagnosis"),
  solution: text("solution"),
  technicianEmail: text("technician_email"),
  laborCents: integer("labor_cents").notNull().default(0),
  partsCents: integer("parts_cents").notNull().default(0),
  totalCents: integer("total_cents").notNull().default(0),
  openedAt: text("opened_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  closedAt: text("closed_at"),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
}, (table) => [uniqueIndex("service_orders_org_number_idx").on(table.organizationId, table.number), index("service_orders_party_idx").on(table.partyId)]);

export const purchaseOrders = sqliteTable("purchase_orders", {
  id: text("id").primaryKey(),
  organizationId: text("organization_id").notNull().references(() => organizations.id),
  supplierId: text("supplier_id").references(() => parties.id),
  number: integer("number").notNull(),
  status: text("status").notNull().default("draft"),
  expectedAt: text("expected_at"),
  totalCents: integer("total_cents").notNull().default(0),
  notes: text("notes"),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
}, (table) => [uniqueIndex("purchase_orders_org_number_idx").on(table.organizationId, table.number)]);

export const financialEntries = sqliteTable("financial_entries", {
  id: text("id").primaryKey(),
  organizationId: text("organization_id").notNull().references(() => organizations.id),
  partyId: text("party_id").references(() => parties.id),
  direction: text("direction").notNull(),
  sourceType: text("source_type").notNull(),
  sourceId: text("source_id"),
  description: text("description").notNull(),
  installment: integer("installment").notNull().default(1),
  installmentCount: integer("installment_count").notNull().default(1),
  amountCents: integer("amount_cents").notNull(),
  dueDate: text("due_date").notNull(),
  paidAt: text("paid_at"),
  status: text("status").notNull().default("open"),
  paymentMethod: text("payment_method"),
  bankReference: text("bank_reference"),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
}, (table) => [index("financial_org_due_idx").on(table.organizationId, table.dueDate), index("financial_party_idx").on(table.partyId)]);

export const bankAccounts = sqliteTable("bank_accounts", {
  id: text("id").primaryKey(),
  organizationId: text("organization_id").notNull().references(() => organizations.id),
  bankCode: text("bank_code").notNull(),
  bankName: text("bank_name").notNull(),
  connector: text("connector").notNull(),
  environment: text("environment").notNull().default("sandbox"),
  branch: text("branch"),
  accountReference: text("account_reference"),
  credentialReference: text("credential_reference"),
  configurationJson: text("configuration_json"),
  status: text("status").notNull().default("not_configured"),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
}, (table) => [index("bank_accounts_org_connector_idx").on(table.organizationId, table.connector)]);

export const bankCharges = sqliteTable("bank_charges", {
  id: text("id").primaryKey(),
  organizationId: text("organization_id").notNull().references(() => organizations.id),
  bankAccountId: text("bank_account_id").notNull().references(() => bankAccounts.id),
  financialEntryId: text("financial_entry_id").references(() => financialEntries.id),
  provider: text("provider").notNull(),
  chargeType: text("charge_type").notNull().default("boleto"),
  externalId: text("external_id"),
  nossoNumero: text("nosso_numero"),
  txid: text("txid"),
  amountCents: integer("amount_cents").notNull(),
  dueDate: text("due_date").notNull(),
  status: text("status").notNull().default("draft"),
  barcode: text("barcode"),
  pixCopyPaste: text("pix_copy_paste"),
  settledAt: text("settled_at"),
  idempotencyKey: text("idempotency_key").notNull(),
  providerResponseJson: text("provider_response_json"),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
}, (table) => [uniqueIndex("bank_charges_org_idempotency_idx").on(table.organizationId, table.idempotencyKey), index("bank_charges_org_status_idx").on(table.organizationId, table.status)]);

export const fiscalDocuments = sqliteTable("fiscal_documents", {
  id: text("id").primaryKey(),
  organizationId: text("organization_id").notNull().references(() => organizations.id),
  partyId: text("party_id").references(() => parties.id),
  model: text("model").notNull(),
  environment: text("environment").notNull().default("homologation"),
  number: integer("number"),
  series: text("series"),
  accessKey: text("access_key"),
  protocol: text("protocol"),
  status: text("status").notNull().default("draft"),
  issueDate: text("issue_date"),
  totalCents: integer("total_cents").notNull().default(0),
  xmlObjectKey: text("xml_object_key"),
  pdfObjectKey: text("pdf_object_key"),
  providerResponseJson: text("provider_response_json"),
  rejectionCode: text("rejection_code"),
  rejectionMessage: text("rejection_message"),
  idempotencyKey: text("idempotency_key").notNull(),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
}, (table) => [uniqueIndex("fiscal_org_idempotency_idx").on(table.organizationId, table.idempotencyKey), index("fiscal_access_key_idx").on(table.accessKey), index("fiscal_org_model_status_idx").on(table.organizationId, table.model, table.status)]);

export const receivedFiscalDocuments = sqliteTable("received_fiscal_documents", {
  id: text("id").primaryKey(),
  organizationId: text("organization_id").notNull().references(() => organizations.id),
  source: text("source").notNull().default("dfe_distribution"),
  model: text("model").notNull(),
  nsu: text("nsu"),
  accessKey: text("access_key").notNull(),
  issuerTaxId: text("issuer_tax_id"),
  issuerName: text("issuer_name").notNull(),
  recipientTaxId: text("recipient_tax_id"),
  issueDate: text("issue_date"),
  receivedAt: text("received_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  totalCents: integer("total_cents").notNull().default(0),
  documentStatus: text("document_status").notNull().default("authorized"),
  manifestationStatus: text("manifestation_status").notNull().default("not_manifested"),
  latestEventCode: text("latest_event_code"),
  xmlObjectKey: text("xml_object_key"),
  distributionResponseJson: text("distribution_response_json"),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
}, (table) => [uniqueIndex("received_fiscal_org_key_idx").on(table.organizationId, table.accessKey), index("received_fiscal_org_model_issue_idx").on(table.organizationId, table.model, table.issueDate), index("received_fiscal_org_manifest_idx").on(table.organizationId, table.manifestationStatus)]);

export const recipientManifestations = sqliteTable("recipient_manifestations", {
  id: text("id").primaryKey(),
  organizationId: text("organization_id").notNull().references(() => organizations.id),
  receivedDocumentId: text("received_document_id").notNull().references(() => receivedFiscalDocuments.id),
  eventType: text("event_type").notNull(),
  eventCode: text("event_code").notNull(),
  sequence: integer("sequence").notNull().default(1),
  justification: text("justification"),
  environment: text("environment").notNull().default("homologation"),
  status: text("status").notNull().default("draft"),
  protocol: text("protocol"),
  registeredAt: text("registered_at"),
  responseJson: text("response_json"),
  idempotencyKey: text("idempotency_key").notNull(),
  createdBy: text("created_by"),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
}, (table) => [uniqueIndex("recipient_manifest_org_idempotency_idx").on(table.organizationId, table.idempotencyKey), index("recipient_manifest_document_idx").on(table.receivedDocumentId), index("recipient_manifest_org_status_idx").on(table.organizationId, table.status)]);

export const fiscalDistributionCursors = sqliteTable("fiscal_distribution_cursors", {
  id: text("id").primaryKey(),
  organizationId: text("organization_id").notNull().references(() => organizations.id),
  service: text("service").notNull().default("nfe_distribution"),
  environment: text("environment").notNull().default("production"),
  lastNsu: text("last_nsu").notNull().default("000000000000000"),
  maxNsu: text("max_nsu"),
  lastStatusCode: text("last_status_code"),
  lastQueryAt: text("last_query_at"),
  nextQueryAllowedAt: text("next_query_allowed_at"),
  status: text("status").notNull().default("idle"),
  lastError: text("last_error"),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
}, (table) => [uniqueIndex("fiscal_distribution_org_service_env_idx").on(table.organizationId, table.service, table.environment)]);

export const recurringContracts = sqliteTable("recurring_contracts", {
  id: text("id").primaryKey(),
  organizationId: text("organization_id").notNull().references(() => organizations.id),
  partyId: text("party_id").notNull().references(() => parties.id),
  productCode: text("product_code").notNull(),
  name: text("name").notNull(),
  billingCycle: text("billing_cycle").notNull().default("monthly"),
  amountCents: integer("amount_cents").notNull(),
  seats: integer("seats").notNull().default(1),
  nextBillingDate: text("next_billing_date"),
  licenseKeyReference: text("license_key_reference"),
  status: text("status").notNull().default("active"),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
}, (table) => [index("contracts_org_status_idx").on(table.organizationId, table.status)]);

export const certificateOrders = sqliteTable("certificate_orders", {
  id: text("id").primaryKey(),
  organizationId: text("organization_id").notNull().references(() => organizations.id),
  partyId: text("party_id").notNull().references(() => parties.id),
  protocol: text("protocol"),
  certificateType: text("certificate_type").notNull(),
  validityMonths: integer("validity_months").notNull().default(12),
  status: text("status").notNull().default("requested"),
  validationMethod: text("validation_method"),
  scheduledAt: text("scheduled_at"),
  issuedAt: text("issued_at"),
  expiresAt: text("expires_at"),
  partnerReference: text("partner_reference"),
  saleCents: integer("sale_cents").notNull().default(0),
  commissionCents: integer("commission_cents").notNull().default(0),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
}, (table) => [index("certificate_orders_org_expiry_idx").on(table.organizationId, table.expiresAt)]);

export const integrationConnections = sqliteTable("integration_connections", {
  id: text("id").primaryKey(),
  organizationId: text("organization_id").notNull().references(() => organizations.id),
  connector: text("connector").notNull(),
  environment: text("environment").notNull().default("homologation"),
  status: text("status").notNull().default("not_configured"),
  credentialReference: text("credential_reference"),
  configurationJson: text("configuration_json"),
  lastHealthCheckAt: text("last_health_check_at"),
  lastError: text("last_error"),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
}, (table) => [uniqueIndex("integration_org_connector_env_idx").on(table.organizationId, table.connector, table.environment)]);

export const auditLogs = sqliteTable("audit_logs", {
  id: text("id").primaryKey(),
  organizationId: text("organization_id").notNull().references(() => organizations.id),
  actorEmail: text("actor_email"),
  action: text("action").notNull(),
  entityType: text("entity_type").notNull(),
  entityId: text("entity_id"),
  beforeJson: text("before_json"),
  afterJson: text("after_json"),
  correlationId: text("correlation_id"),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
}, (table) => [index("audit_org_created_idx").on(table.organizationId, table.createdAt)]);

export const fiscalEstablishments = sqliteTable("fiscal_establishments", {
  id: text("id").primaryKey(),
  organizationId: text("organization_id").notNull().references(() => organizations.id),
  legalName: text("legal_name").notNull(),
  tradeName: text("trade_name"),
  taxId: text("tax_id").notNull(),
  stateRegistration: text("state_registration"),
  municipalRegistration: text("municipal_registration"),
  taxRegime: text("tax_regime").notNull().default("simples_nacional"),
  cnae: text("cnae"),
  cityCode: text("city_code"),
  state: text("state").notNull().default("RS"),
  nfeSeries: text("nfe_series").notNull().default("1"),
  nextNfeNumber: integer("next_nfe_number").notNull().default(1),
  environment: text("environment").notNull().default("homologation"),
  certificateReference: text("certificate_reference"),
  certificateExpiresAt: text("certificate_expires_at"),
  credentialStatus: text("credential_status").notNull().default("pending"),
  taxProfileStatus: text("tax_profile_status").notNull().default("pending"),
  status: text("status").notNull().default("configuration_pending"),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
}, (table) => [uniqueIndex("fiscal_establishments_org_tax_idx").on(table.organizationId, table.taxId)]);

export const nfeDrafts = sqliteTable("nfe_drafts", {
  id: text("id").primaryKey(),
  organizationId: text("organization_id").notNull().references(() => organizations.id),
  establishmentId: text("establishment_id").references(() => fiscalEstablishments.id),
  partyId: text("party_id").references(() => parties.id),
  natureOperation: text("nature_operation").notNull(),
  purpose: text("purpose").notNull().default("normal"),
  operationType: text("operation_type").notNull().default("output"),
  destinationType: text("destination_type").notNull().default("internal"),
  finalConsumer: integer("final_consumer", { mode: "boolean" }).notNull().default(false),
  presenceIndicator: text("presence_indicator").notNull().default("not_applicable"),
  freightMode: text("freight_mode").notNull().default("no_freight"),
  series: text("series").notNull().default("1"),
  environment: text("environment").notNull().default("homologation"),
  status: text("status").notNull().default("draft"),
  recipientName: text("recipient_name").notNull(),
  recipientTaxId: text("recipient_tax_id").notNull(),
  recipientStateRegistration: text("recipient_state_registration"),
  recipientEmail: text("recipient_email"),
  recipientState: text("recipient_state"),
  recipientCityCode: text("recipient_city_code"),
  productsTotalCents: integer("products_total_cents").notNull().default(0),
  freightCents: integer("freight_cents").notNull().default(0),
  discountCents: integer("discount_cents").notNull().default(0),
  otherCents: integer("other_cents").notNull().default(0),
  totalCents: integer("total_cents").notNull().default(0),
  notes: text("notes"),
  validationStatus: text("validation_status").notNull().default("pending"),
  validationJson: text("validation_json"),
  idempotencyKey: text("idempotency_key").notNull(),
  createdBy: text("created_by"),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
}, (table) => [uniqueIndex("nfe_drafts_org_idempotency_idx").on(table.organizationId, table.idempotencyKey), index("nfe_drafts_org_status_idx").on(table.organizationId, table.status, table.createdAt)]);

export const nfeDraftItems = sqliteTable("nfe_draft_items", {
  id: text("id").primaryKey(),
  draftId: text("draft_id").notNull().references(() => nfeDrafts.id),
  itemNumber: integer("item_number").notNull(),
  catalogItemId: text("catalog_item_id").references(() => catalogItems.id),
  description: text("description").notNull(),
  ncm: text("ncm").notNull(),
  cest: text("cest"),
  cfop: text("cfop").notNull(),
  unit: text("unit").notNull().default("UN"),
  quantityMilli: integer("quantity_milli").notNull(),
  unitPriceCents: integer("unit_price_cents").notNull(),
  totalCents: integer("total_cents").notNull(),
  origin: text("origin").notNull().default("0"),
  cst: text("cst"),
  csosn: text("csosn"),
  icmsJson: text("icms_json"),
  pisJson: text("pis_json"),
  cofinsJson: text("cofins_json"),
  taxReformJson: text("tax_reform_json"),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
}, (table) => [uniqueIndex("nfe_draft_items_number_idx").on(table.draftId, table.itemNumber), index("nfe_draft_items_draft_idx").on(table.draftId)]);

export const fiscalTransmissionQueue = sqliteTable("fiscal_transmission_queue", {
  id: text("id").primaryKey(),
  organizationId: text("organization_id").notNull().references(() => organizations.id),
  fiscalDocumentId: text("fiscal_document_id").references(() => fiscalDocuments.id),
  nfeDraftId: text("nfe_draft_id").references(() => nfeDrafts.id),
  operation: text("operation").notNull().default("authorization"),
  environment: text("environment").notNull().default("homologation"),
  status: text("status").notNull().default("blocked"),
  endpointVersion: text("endpoint_version").notNull().default("4.00"),
  schemaVersion: text("schema_version").notNull().default("010e_v1.01"),
  attempts: integer("attempts").notNull().default(0),
  maxAttempts: integer("max_attempts").notNull().default(5),
  nextAttemptAt: text("next_attempt_at"),
  credentialReference: text("credential_reference"),
  idempotencyKey: text("idempotency_key").notNull(),
  lastError: text("last_error"),
  requestReference: text("request_reference"),
  responseJson: text("response_json"),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
}, (table) => [uniqueIndex("fiscal_queue_org_idempotency_idx").on(table.organizationId, table.idempotencyKey), index("fiscal_queue_org_status_idx").on(table.organizationId, table.status, table.nextAttemptAt)]);

export const syncDevices = sqliteTable("sync_devices", {
  id: text("id").primaryKey(),
  organizationId: text("organization_id").notNull().references(() => organizations.id),
  name: text("name").notNull(),
  platform: text("platform").notNull(),
  installationId: text("installation_id").notNull(),
  tokenHash: text("token_hash").notNull(),
  appVersion: text("app_version"),
  status: text("status").notNull().default("active"),
  lastSeenAt: text("last_seen_at"),
  lastSyncCursor: integer("last_sync_cursor").notNull().default(0),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
}, (table) => [uniqueIndex("sync_devices_token_idx").on(table.tokenHash), uniqueIndex("sync_devices_org_installation_idx").on(table.organizationId, table.installationId), index("sync_devices_org_status_idx").on(table.organizationId, table.status)]);

export const devicePairingCodes = sqliteTable("device_pairing_codes", {
  id: text("id").primaryKey(),
  organizationId: text("organization_id").notNull().references(() => organizations.id),
  codeHash: text("code_hash").notNull(),
  expiresAt: text("expires_at").notNull(),
  usedAt: text("used_at"),
  createdBy: text("created_by"),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
}, (table) => [uniqueIndex("device_pairing_code_hash_idx").on(table.codeHash), index("device_pairing_org_expiry_idx").on(table.organizationId, table.expiresAt)]);

export const syncOperations = sqliteTable("sync_operations", {
  id: text("id").primaryKey(),
  organizationId: text("organization_id").notNull().references(() => organizations.id),
  deviceId: text("device_id").references(() => syncDevices.id),
  operationId: text("operation_id").notNull(),
  entityType: text("entity_type").notNull(),
  entityId: text("entity_id"),
  action: text("action").notNull(),
  payloadHash: text("payload_hash"),
  status: text("status").notNull().default("applied"),
  resultJson: text("result_json"),
  processedAt: text("processed_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
}, (table) => [uniqueIndex("sync_operations_org_operation_idx").on(table.organizationId, table.operationId), index("sync_operations_device_created_idx").on(table.deviceId, table.createdAt)]);

export const syncChangeLog = sqliteTable("sync_change_log", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  organizationId: text("organization_id").notNull().references(() => organizations.id),
  deviceId: text("device_id").references(() => syncDevices.id),
  entityType: text("entity_type").notNull(),
  entityId: text("entity_id").notNull(),
  action: text("action").notNull(),
  version: integer("version").notNull().default(1),
  payloadJson: text("payload_json"),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
}, (table) => [index("sync_change_org_cursor_idx").on(table.organizationId, table.id), index("sync_change_entity_idx").on(table.organizationId, table.entityType, table.entityId)]);
